### ISSUE TITLE
--assume-individual-stock does not work

### ISSUE THREAD

**Issue by doschu** [laroche/tastyworks-pnl#1]
I changed it to:

`        if opt in ('--assume-individual-stock')`

then it works in my local branch. Also I cannot push to the repo. Mind marking me as collaborator?

**Comment by laroche** [comment]
This seems to work ok for me, but with the newest code I had to change the getopt call
to be correct.

Can you please update to the newest version and try again? If it does not work, please post
the traceback and python version, then I'll also try to replicate it on a similar python/Linux version.

The repo should be open for merge request and I am happy to take them, but for now I first want
to review proposed changes.

Thanks a lot,
best regards,

Florian La Roche

**Comment by doschu** [comment]
Works now...

thank you
