### ISSUE TITLE
Cryptos fail on quantity

### ISSUE THREAD

**Issue by deicon** [laroche/tastyworks-pnl#10]
As cryptos are bought in fractions this check here fails. 

int(quantity) != quantity 

if isnan(quantity):
            quantity = 1
        else:
            if tcode == 'Receive Deliver' and (tsubcode == 'Forward Split' or tsubcode == 'Reverse Split'):
                pass # splits might have further data, not quantity
            elif int(quantity) != quantity:
                raise
            else:
                quantity = int(quantity)

**Comment by laroche** [comment]
I have no experience with cryptos. Is this check the only thing that breaks? Should cryptos be within a new trading group?
(Are you buying cryptos directly with Tastyworks or a derivative product?)
How can they be detected? With a list of symbol names? Then I could remove this check only for cryptos and keep it for
everything else.

Thanks for this feedback,

Florian La Roche

**Comment by deicon** [comment]
2021-09-03T20:50:34+0200,Trade,SELL_TO_CLOSE,ETH/USD,Cryptocurrency,Sold 0.2637329 ETH/USD @ 3948.01,"1,041.22",0.2637329,"3,948.01",-10.00,0.00,,,,,,,11111111
2021-09-02T21:33:54+0200,Trade,BUY_TO_OPEN,ETH/USD,Cryptocurrency,Bought 0.2637329 ETH/USD @ 3791.71,"-1,000.00",0.2637329,"-3,791.72",-10.00,0.00,,,,,,,111111111

**Comment by deicon** [comment]
I believe cryptos need to be handled in their own group as far as I understand our tax system. Which I don't really :)

**Comment by laroche** [comment]
The above entry seems to come from the Desktop App, right? Can you provide them from the web download,
then I might finish some first support for cryptos based on that.

Thanks a lot,

Florian La Roche

**Comment by laroche** [comment]
Crypto support is merged into the current version. Since I am not using it myself, please
open a new issue if further changes are needed. I think the above example should work ok.

best regards,

Florian La Roche
