### ISSUE TITLE
Download Limit Transaction History

### ISSUE THREAD

**Issue by deicon** [laroche/tastyworks-pnl#12]
Currently, the only simple way to download all transactions in one go, one needs to use 
the desktop application. Downloads within the web version is limited to 250 lines. 

Sadly both formats differ. Do you know how much effort it might be to adjust the code to understand the format from the Desktop Apps Exports ?

Using the web frontend works, but only with a lot of manual steps which lead to errors and possibly missing transactions.

**Comment by laroche** [comment]
Something like trading fees was missing from the Desktop App Exports, but I haven't checked this recently.
I might make sense to support both downloads in the future.

**Comment by laroche** [comment]
The different downloads with different formats are a source for misunderstanding.
I do not plan of adding support for the Desktop App, but will help if anyone wants to merge such
support into the source code.

closing this issue,
feel free to open a new issue if questions come up,

Florian La Roche
