### ISSUE TITLE
Verlustverrechnungsbeschränkung 2021

### ISSUE THREAD

**Issue by mappold** [laroche/tastyworks-pnl#13]
Hi @laroche, great tool! Does it also support the new "Verlustverrechnungsbeschränkung für Termingeschäfte bis 20.000€" introduced in 2021? I saw there is a parameter `term_loss` but I'm unsure if I can just set it to 20000 and that's it? Thank you

**Comment by laroche** [comment]
With normal text output, you can see a line like "losses future contracts:     -375.62€", so you can check this stays below the 20K€ amount (or 40K€ for couples).
Even better is to look into the tax-report output (csv-file). There you can check the summary line "Long-Optionen Verluste".

best regards,
good luck,

Florian La Roche

**Comment by alneven** [comment]
@laroche ist es wirklich 40k EUR für das Paar? Nice to know ;)

**Comment by laroche** [comment]
For official answer please contaxt a tax advisor.

I think if you have a common depot at a broker, this 20k limit is used per person, so you have a 40k limit per year.

The new summary output now has a "Z24 Termingeschäftsverluste", so generating a current status for this
20k limit is easily available.

closing this report,
feel free to open a new issue if you have followup questions,

Florian La Roche
