### ISSUE TITLE
Missing fees

### ISSUE THREAD

**Issue by sebastianhaberey** [laroche/tastyworks-pnl#14]
Hi @laroche,

I love this tool and also the information you compiled about german tax law. Thank you so much, it's really very useful! I was going mad trying to do this in Libre Office.

I have one question regarding the fees. Following the instructions, I downloaded the transaction history on the web site and combined all data in one file. The script runs and finishes successfully. But while the source data has a _Fees_ column with valid values, they are not included in the _Ordergebühren_ column, nor elsewhere.

For my Lynx account I always put the fees in the tax form to be deducted. So my question is - is this intentional?

**Comment by laroche** [comment]
Order fees are already deducted in the tax statement for each individual trade. Just the extra small cent payments are still kept separat and are not assigned to an individial trade. Original goal was to keep the tax statement small, but maybe I should add again more data and people can reduce again the output if wanted.

(So the trade price is already reduced by all order fees. Please let me know if this is not the case.)

best regards,

Florian La Roche

**Comment by sebastianhaberey** [comment]
Yes, I can confirm the fees are processed correctly.

For my excel sheet I used the "2021 Year-to-Date Data Export" that can be downloaded in _Account Management > My Account > Tax Center_. This export has the fees already included in the _COST_ and _PROCEEDS_ columns.

I used the same currency data as you did.

The result is (almost) identical with that of your script. The end result differs by 0,04 EUR which is the result of rounding differences between the "2021 Year-to-Date Data Export" downloaded from Account Management versus the "Transaction History" downloaded from the web application.

So all good 🙂

**Comment by laroche** [comment]
Oh good. The tax report uses rounding with 2 digits and I can also see small rounding errors.

Without rounding I can use the numbers with 4 digit precision from Tastyworks and even with 4 years of
data, then end cash result is exactly the same without a cent difference between the script calculations
and comparing the end cash result with the cash sum reported by Tastyworks.

best regards,

Florian La Roche

**Comment by sebastianhaberey** [comment]
Oh, you're right, the transaction history _does_ have 4 digit precision. So that makes sense too.
