### ISSUE TITLE
Calculation of column "usd_gains"

### ISSUE THREAD

**Issue by sebastianhaberey** [laroche/tastyworks-pnl#15]
Hi @laroche,

This is a tax law question rather than an issue: Why is the _usd_gains_ column calculated the way it is? I can see that there's values in this column when option positions are _opened_ and no values when they are closed. I'd have expected it the other way around, but my knowledge of the tax law isn't great. Could you explain why _Währungsgewinne_ are calculated that way (or point me to an article)?

**Comment by laroche** [comment]
Hello Sebastian,

usd_gains are calculated on the cash, so buying a stock sells usd and that is the time
you are using FIFO to calculate the tax gains. (So if you are opening a long option position, that's
exactly the same as with stock. Short selling is the opposite...)

General info about all this:
https://laroche.github.io/private-geldanlage/steuern.html#fremdwaehrungskonten

best regards,

Florian La Roche

**Comment by sebastianhaberey** [comment]
Ok, thanks! One question though: wouldn't you have to know the initial exchange rate for this? I mean, the exchange rate that was applied when I transferred the money to my Tastyworks account?

**Comment by laroche** [comment]
Correct. You need to input a complete transaction set to get correct output for all FIFO calculations.
If you then specify a certain tax year, only the output is limited to that time period.

**Comment by sebastianhaberey** [comment]
So how do you figure out the exchange rate of the initial transfer, since it's not in the input data? Do you just take the exchange rate valid on the day of transfer?

**Comment by laroche** [comment]
Exchange rates are from bundesbank.de.

best regards,

Florian La Roche

**Comment by laroche** [comment]
Closing this issue, feel free to open up a new issue if further questions come up.

best regards,

Florian La Roche
