### ISSUE TITLE
Blew up my account but tool says I made gains - did I do something wrong?

### ISSUE THREAD

**Issue by XNet80** [laroche/tastyworks-pnl#16]
Hi @laroche 
I just used your tool to calculate my Tastyworks tax. Thank you so much fro providing this service.
But to be honest I'm a bit confused by the result.

Basically I blew up my account in 2021. All my gains and most of my initial deposit was gone by the end of 2021.
The tool however calculated about 50% more gains than losses for that year under "Long-Optionen" and about 98% under "Stillhalter".

Did I do something wrong? Or just misunderstood something?

Thanks ins advance.

**Comment by XNet80** [comment]
Thanks for answering. I'm covering the Stillhalter stuff first, because it's only two positions:
I opened a STO position for 0.17 USD and later closed it BTC for 0.18 USD.
Here are the lines from my Tastyworks transaction CSV which I used with your tool:

01/14/2021 3:56 PM | Trade | Sell to Open | GME | Sell | Open | 1 | 07/16/2021 | 5 | P | 0.17 | 1152 | 17 | Sold 1 GME 07/16/21 Put 5.00 @ 0.17 | Individual

03/01/2021 4:01 PM | Trade | Buy to Close | GME | Buy | Close | 1 | 07/16/2021 | 5 | P | 0.18 | 0.14 | -18 | Bought 1 GME 07/16/21 Put 5.00 @ 0.18 | Individual

Here's what the PNL tool put out in its CSV:

2021-01-14 | Stillhalter-Option | 936.16 | -936.16 | -1135.00 | 1.2124 | -1 | GME P5 21-07-16 | True | 0.00 | 0.00

2021-03-01 | Stillhalter-Option | -15.05 | -15.05 | -18.14 | 1.2053 | 1 | GME P5 21-07-16 | False | 0.00 | 0.00

The second case something similar happened. I STO for 0.46 USD and BTC for 0.22 USD but the tool says I STO for 11.06 USD

Any idea how this happened?

**Comment by XNet80** [comment]
Here's an example from my long options. 
I bought a 0DTE Call for 39.14 USD which expired worthless (was automatically sold for $1)
Here are the lines from my Tastyworks transaction CSV which I used with your tool:

01/15/2021 3:30 PM | Trade | Buy to Open | GME | Buy | Open | 1 | 01/15/2021 | 47 | C | 0.38 | 1.14 | -38 | Bought 1 GME 01/15/21 Call 47.00 @ 0.38 | Individual

01/15/2021 9:25 PM | Trade | Sell to Close | GME | Sell | Close | 1 | 01/15/2021 | 47 | C | 0.01 | 152 | 1 | Sold 1 GME 01/15/21 Call 47.00 @ 0.01 | Individual

The PNL tool however thinks I made a profit of over $90:

2021-01-15 | Long-Option | 0.00 | -32.29 | -39.14 | 1.2123 | 1 | GME C47 21-01-15 | False | 0.00 | 0.00

2021-01-15 | Long-Option | 92.27 | -124.56 | -151.00 | 1.2123 | -1 | GME C47 21-01-15 | False | 0.00 | 0.00

**Comment by laroche** [comment]
Your very first line from Tastyworks CSV:
- It contains "17" as cash amount in USD for this transaction which looks right.
- Right before this are the fees for this transaction and it lists "1152", which would mean that Tastyworks would bill a 1152 USD on fees for it. My script computes overall transaction with "amount - fees" = 17 - 1152 = -1135 USD as overall transaction for this item.

This looks like you probably have fees of "1.152" USD (a bit more than one USD, not more than a thousand dollars.

Looks like "," and "." for thousand are not set correctly for data processing.

Can you check if using LANG=de_DE.UTF-8 right at the begging of your command line gives correct processing?
("locale -a" gives a list of working locale settings.) Are you running the script with en_US locale settings?

best regards,

Florian La Roche

**Comment by laroche** [comment]
Btw second line for Stillhalter GME looks all right, closing trade:  18 USD to buy back the option and 0.14 USD with fees gives overall cost of $18.14 with a EURUSD conversion of 1.2053 results 15.05 Euro costs to close this trade.

best regards,

Florian La Roche

**Comment by laroche** [comment]
I had one report where opening and then storing data with Excel changes values. Can you run the
scrip directly on the data from Tastyworks? If you have to combine data from several files into one,
maybe you can use a normal text  editor instead of a spreadsheet program?

best regards,

Florian La Roche

**Comment by XNet80** [comment]
I just saw your last answer. That's exactly what happened. Somehow when combining several files in LibreOffice it changed fees of -0.1152 to +1152.
I re-downloaded all my transactions and combined them in the text editor. Now the report looks correct: 1000 Euro losses instead of 6000 Euro gains ;-)
