### ISSUE TITLE
[question] Detail list like last year

### ISSUE THREAD

**Issue by alneven** [laroche/tastyworks-pnl#17]
hello @laroche / Florian,

last year I've prepared somehow a detailed list about my trades like this
(https://imgur.com/a/ArF1UGR)

now I have something total different, is there any switch I can create this again?
thank you!

**Comment by alneven** [comment]
humm, or maybe it was me who created this based on the output csv ?! :suspect:

**Comment by laroche** [comment]
This was output as normal text, but was never very good to maintain.

Current best way is to use "--output-csv=tax.csv" to generate a new CSV file with
all information. And with a spreadsheet program you can easily add/remove a few columns
for a final report.

best regards,

Florian La Roche

**Comment by laroche** [comment]
I've added a "--verbose" Option which outputs the transaction list as text.
Though I recommend to use the CSV output file for further processing.

All data from the old text output is now included into the output csv or the summary csv.

Closing this request for now. Please re-open with new data or a new request if you feel
strongly about further changes to the current version and how they should look like.

best regards from Germany,

Florian La Roche
