### ISSUE TITLE
Unterschied "Stillhalter Gesamt" und "Stillhalter Gesamt (FIFO)"

### ISSUE THREAD

**Issue by flanello** [laroche/tastyworks-pnl#27]
Was ist der Unterschied zwischen "Stillhalter Gesamt" und "Stillhalter Gesamt (FIFO)" in der 2021 Auswertung?
Und warum wird "Stillhalter Gesamt" für die Angabe in Z21 verwendet?

**Comment by laroche** [comment]
Bei FIFO (First In First Out) wird alles wie bei Aktien berechnet. Die andere Berechnung nimmt einfach den Betrag
und trägt ihn direkt für die Steuer ein. Bei Stillhaltergeschäften wird die eingenommene Prämie direkt versteuert
und beim Glattstellen wird der Betrag als Verlustgeschäft gegengerechnet. Im Gesetz steht, dass der Glattstellungsbetrag
die vereinnahmte Prämie mindert.
Beide Werte sollten für die Steuer ok sein, ich sehe nicht, wie ein Wert hier im Gesetzestext eindeutig hervorgeht.
Wenn man Optionen lange offen lässt, kann man solange die Steuer nicht abgeben, wie Positionen noch offen sind, wenn
man nach FIFO vorgeht.

Ich sehe auch nicht, wie Z21 überhaupt für die Berechnung der Steuer verwendet werden kann. Die Zeile scheint
ein Überbleibsel aus der Vergangenheit zu sein.

Eine echte juristische Einschätzung dazu würde mir sehr helfen.

Viele Grüße,

Florian La Roche

**Comment by flanello** [comment]
Thx.
