### ISSUE TITLE
Support für den CSV Export aus der Plattform

### ISSUE THREAD

**Issue by MiErnst** [laroche/tastyworks-pnl#28]
Hi,
warum wird eigentlich in dem Tool auf den WebClient für den CSV Download verwiesen? Warum kann man nicht den von der Plattform generierten nehmen. Eigentlich müsste doch das der gleiche Inhalt sein. Das zusammenfriemeln der CSV ist sehr anfällig für manuelle Fehler. Der Export aus der Plattform hat die 250 Zeilen Datensatzbegrenzung nicht.

Altrnativ, wäre es möglich, dass man statt einer einzelnen CSV einen Ordner voller CSVs als Input nehmen kann und das Tool kümmert sich daraum daraus einen validen Datensatz zu bauen wobei Duplikate z.B. in den Exports automatisch entfernt werden.

**Comment by laroche** [comment]
Das neue Format ist nun unterstützt. Ich konnte mal alle Transaktionen mit einem einzelnen Download
herunterladen. Damit sollte man nun die Auswertung gut hinbekommen.

Falls nochmal neue Rückmeldungen aufkommen, bitte nochmal einen neuen Request aufmachen.

Vielen Dank,
Viele Grüße,

Florian La Roche
