### ISSUE TITLE
No such file or directory; 'soffice' error although libbre office is installed

### ISSUE THREAD

**Issue by ss85s** [laroche/tastyworks-pnl#32]
The following command : python tw-pnl.py --assume-individual-stock --tax-output=2022 --output-csv=tastyworks-tax-2022.csv transaction_history.csv soffice tastyworks-tax-2022.csv

fails with error: No such file or directory; 'soffice' 

<img width="882" alt="image" src="https://user-images.githubusercontent.com/63041412/210076655-bc22f3fe-898b-4f51-a83f-91db6895d6cf.png">

**Comment by laroche** [comment]
Bitte einfach die letzten 2 Worte weglassen. Damit wird die CSV-Eingabedatei mit dem Skript in eine CSV-Ausgabedatei umgeschrieben. Erst anschliessend sollte man diese CSV-Ausgabedatei mit libreoffice öffnen.

mfg,

Florian La Roche

**Comment by ss85s** [comment]
[tastyworks-tax-2022.csv](https://github.com/laroche/tastyworks-pnl/files/10325866/tastyworks-tax-2022.csv)
Hi Florian,

danke für die schnelle Antwort. Erhalte nun den folgenden Fehler für die angehängte CSV Datei:

Traceback (most recent call last):
  File "C:\Users\snsr\Downloads\tastyworks-pnl-main\tastyworks-pnl-main\tw-pnl.py", line 1148, in <module>
    main(sys.argv[1:])
  File "C:\Users\snsr\Downloads\tastyworks-pnl-main\tastyworks-pnl-main\tw-pnl.py", line 1145, in main
    check(all_wk, output_summary, output_csv, output_excel, tax_output, show, verbose, debug)
  File "C:\Users\snsr\Downloads\tastyworks-pnl-main\tastyworks-pnl-main\tw-pnl.py", line 986, in check
    (tsubcode in ('Expiration', 'Exercise', 'Assignment', 'Cash Settled Assignment', 'Cash Settled Exercise') and not fifos_islong(fifos, asset))):
  File "C:\**\tastyworks-pnl-main\tastyworks-pnl-main\tw-pnl.py", line 387, in fifos_islong
    return fifos[asset][0][2] > 0
**KeyError: 'GOLD C16 22-10-21'**

**Comment by laroche** [comment]
Die Eingabedatei ist nicht vollständig. Die unterste Zeile verkauft einen GOLD Call, anschliessend (vorletzte Zeile)
wird der GOLD-Call geschlossen. Dritte Zeile von unten wird ein GOLD Put geschlossen, der ja aber gar nicht existieren kann, wenn die Datei vollständig sein soll.

Viele Grüße aus Stuttgart,

Florian La Roche

**Comment by laroche** [comment]
Falls noch etwas offen ist, bitte mit mehr Informationen wieder öffnen oder ein neues Issue erstellen.

Viele Grüße aus Stuttgart,

Florian La Roche
