### ISSUE TITLE
"Z19 Ausländische Kapitalerträge" ohne Verluste aus Termingeschäften

### ISSUE THREAD

**Issue by thomasschuster** [laroche/tastyworks-pnl#33]
Hallo Florian,

vielen Dank für die tolle Arbeit, die du mit diesem Tool geleistet hast. Ich habe meine für 2022 zu zahlende Steuer über das Feld "KAP+KAP-INV KErSt+Soli" gecheckt und war über den hohen Wert überrascht. Dann ist mir aufgefallen, dass du wie in https://laroche.github.io/private-geldanlage/steuern.html dokumentiert in Z19 keine Verluste aus Termingeschäften subtrahierst.

Ich habe daraufhin zwei Demo-Termingeschäfte (Long Calls auf Aktien) erstellt und mir die Konsolenausgabe angeschaut. Hier werden bei zwei Trades knapp 20k Verlust erzielt und dann knapp 20k Gewinn.

Date/Time,Transaction Code,Transaction Subcode,Symbol,Buy/Sell,Open/Close,Quantity,Expiration Date,Strike,Call/Put,Price,Fees,Amount,Description,Account Reference
01/08/2023 3:36 PM,Trade,Sell to Close,AMD,Sell,Close,1,10/21/2023,80,P,250.00,0.142,25000,Sold 1 AMD 10/21/23 Put 80.00 @ 250.00,4711
01/07/2023 4:05 PM,Trade,Buy to Open,AMD,Buy,Open,1,10/21/2023,80,P,50,1.13,-5000,Bought 1 AMD 10/21/23 Put 80.00 @ 50.00,4711
01/06/2023 3:36 PM,Trade,Sell to Close,AMD,Sell,Close,1,10/21/2023,80,P,50,0.142,5000,Sold 1 AMD 10/21/23 Put 80.00 @ 50.00,4711
01/05/2023 4:05 PM,Trade,Buy to Open,AMD,Buy,Open,1,10/21/2023,80,P,250.00,1.13,-25000,Bought 1 AMD 10/21/23 Put 80.00 @ 250.00,4711

Unter dem Strich hätte ich dann eine Steuerschuld um die 0 erwartet. Das Tool sagt aber folgendes:

...
Long-Optionen-Gewinne                   19046.41
Long-Optionen-Verluste                 -18821.98
Long-Optionen Gesamt                      224.43
...
Z19 Ausländische Kapitalerträge         19046.41
Z21 Termingeschäftsgewinne+Stillhalter  19046.41
Z24 Termingeschäftsverluste            -18821.98
KAP+KAP-INV                             19046.41
KAP+KAP-INV KErSt+Soli                   5023.49
KAP+KAP-INV Verlustvortrag                  0.00
...

Mir ist aufgefallen, dass in meinem Interactive Brokers German Tax Report in Z19 "losses from trading in derivatives" bereits abgezogen sind und bin jetzt leicht verwirrt. Zum einen, welchen Wert ich bei meiner Steuererklärung in Z19 eintragen soll und zum anderen, warum mir eine Steuerlast von über 5k angezeigt wird. Vielleicht kannst du mir hier auf die Sprünge helfen.

Keep up the good work, viele Grüße,
Thomas

**Comment by thomasschuster** [comment]
Als follow up, habe da gerade nochmal reingeschaut, wenn ich in Z19 Termingeschäftsverluste bis zur Grenze von 20k zulasse

if z24 >= -20000:
    stats.loc['Z19 Ausländische Kapitalerträge', year] += z24
else:
    stats.loc['Z19 Ausländische Kapitalerträge', year] -= 20000

 
 dann erhalte ich das von mir als Laie erwartete Ergebnis:
 
 Long-Optionen-Gewinne                   19046.41
Long-Optionen-Verluste                 -18821.98
Long-Optionen Gesamt                      224.43
...
Z19 Ausländische Kapitalerträge           224.43
Z21 Termingeschäftsgewinne+Stillhalter  19046.41
Z24 Termingeschäftsverluste            -18821.98
KAP+KAP-INV                               224.43
KAP+KAP-INV KErSt+Soli                     59.19

**Comment by laroche** [comment]
Wie die einzelnen Börsen-Einnahmen eingetragen werden habe ich hier dokumentiert:
<https://laroche.github.io/private-geldanlage/steuern.html#KAP2021>
Ich glaube die Tabelle ist korrekt.

In dem Skript ist ein Verlustvortrag für Aktien und für die Anlage SO implementiert, aber keine
Kappung auf 20K für Termingeschäfte. Es fehlt also ein Verlusttopf.
Nur für die Gesamtsumme ist dann nochmal ein Verlusttopf vorgesehen, nachdem da aber so schnell noch ein
paar andere Faktoren reinspielen, ist der doch etwas unsicher für mich.

Die Berechnungen sind im Skript recht einfach nachzuvollziehen, selbst wenn man nicht viel
Programmieren kann. Im Skript ab ca Zeile 700 ist der Gesamtbetrag zu sehen, die Zeilen davor
zeigen alle anderen Berechnungen recht deutlich.



Nochmal zurück zum IB EY-Report: Ist natürlich klasse, wenn die Termingeschäftsverluste in Z19 auch nochmal
abgezogen werden können. Ich habe gehört, dass man alle Eintragungen in der Steuer nur an einer Stelle
eintragen darf und nicht mehrfach. Z20 bis Z23 sind davon explizit ausgeschlossen.
Hier würde ich mich freuen, wenn jemand fertige Steuerberichte durchschauen/nachrechnen kann und
damit diesen Weg bekräftigen kann.
Sollte dies nicht der Fall sein, dann sollte man sofort Einspruch einlegen und noch die Verluste richtig eintragen lassen.


Viele Grüße,

Florian La Roche

**Comment by laroche** [comment]
Ja, Termingeschäftsverluste müssen noch richtig eingetragen werden. Patch dazu willkommen, vielleicht
komme ich sonst in ein paar Tagen auch mal dazu.

Danke für die Infos,
Gruss,

Florian La Roche

**Comment by laroche** [comment]
Berechnungen für die Steuer sind alle richtig, hier geht es nur um eine Anpassung für die Steuerberechnung, die ja normalerweise vom Finanzamt kommt.

Ich habe einen Verlusttopf für Termingeschäfte eingerichtet. Termingeschäftsvreluste sind damit auf 20.000 Euro
begrenzt.

Über Tests dazu würde ich mich freuen. "KAP+KAP-INV" hat nun die Termingeschäftsverluste mit abgezogen,
daher sollte dort der Steuerbetrag richtig niedrig sein.

Passt das?

Viele Grüße,

Florian La Roche

**Comment by thomasschuster** [comment]
Vielen Dank für die rasche Anpassung, schon ist meine Steuerschuld im erwarteten Bereich. Und danke für die Klarstellung zu Z19. Das Finanzamt zieht dann am Ende von der Summe aller vorhandenen Trading-Accounts den max. Betrag ab (20k oder 40k). Wenn man ausschließlich bei tastyworks handelt, sieht man jetzt direkt den richtigen Betrag, optimal.

Viele Grüße,
Thomas
