### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by XNet80** [laroche/tastyworks-pnl#36]
When running the script I get the following error:
File "tw-pnl.py", line 186, in <module>
    SP500: tuple[str, ...] = ('A', 'AAL', 'AAP', 'AAPL', 'ABBV', 'ABC', 'ABT', 'ACGL', 'ACN', 'ADBE',
TypeError: 'type' object is not subscriptable

Any idea what that means?

**Comment by laroche** [comment]
What version of python and what OS are you running on?

Is it fixed by just changing to:
SP500 = (...

These "new" type annotations should usually just be ignored,
not sure if this is indeed an error on my side,
best regards,

Florian La Roche

**Comment by XNet80** [comment]
It was in Anaconda on Windows 11. I uninstalled Anaconda and tried again. Now I'm getting a new error:

 C:\Users\XXX\tastyworks-pnl-main\tw-pnl.py:1160: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  wk = pandas.read_csv(csv_file, parse_dates=['Date/Time'])
Traceback (most recent call last):
  File "C:\Users\XXX\tastyworks-pnl-main\tw-pnl.py", line 1254, in <module>
    main(sys.argv[1:])
  File "C:\Users\XXX\tastyworks-pnl-main\tw-pnl.py", line 1251, in main
    check(all_wk, output_summary, output_csv, output_excel, tax_output, show, verbose, debug)
  File "C:\Users\XXX\tastyworks-pnl-main\tw-pnl.py", line 1051, in check
    (tsubcode in ('Expiration', 'Exercise', 'Assignment', 'Cash Settled Assignment', 'Cash Settled Exercise') and not fifos_islong(fifos, asset))):
                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\XXX\tastyworks-pnl-main\tw-pnl.py", line 392, in fifos_islong
    return fifos[asset][0][2] > 0
           ~~~~~^^^^^^^
KeyError: 'SPCE C15 21-12-31'

**Comment by laroche** [comment]
Usually this means the history of trades is not complete. Can you run with a complete
data set?

best regards,

Florian La Roche

**Comment by laroche** [comment]
Best is to include all data from the beginning of the account. You can limit the output to certain
years for tax purposes. The above error is closing an option position for SPCE, but theere is no
opening position available.

I am using "RUN.sh" on Linux to get all output years. This is about the syntax for an individual year:
python3 tw-pnl.py $PARAM --tax-output=$year --output-csv=$OUTPUTDIR/tax-$year.csv $INPUT

best regards,

Florian La Roche

**Comment by XNet80** [comment]
Including more data was the issue. Thanks very much for helping.
