### ISSUE TITLE
 Wrong first line in csv file

### ISSUE THREAD

**Issue by ayzakaria** [laroche/tastyworks-pnl#37]
Hi,

I have download the transaction history from the tastytade web page but it doesnt match the expected format.
It is in this format : Date,Type,Action,Symbol,Instrument Type,Description,Value,Quantity,Average Price,Commissions,Fees,Multiplier,Root Symbol,Underlying Symbol,Expiration Date,Strike Price,Call or Put,Order #

**Comment by laroche** [comment]
Hello ayzakaria,

I've just checked this myself. Seems they have launched a new website and coverted
the history file to this new format.

I want to change the script to this new format, but haven't found time for
this change until now.

best regards,

Florian La Roche

**Comment by laroche** [comment]
You can still download the old style history by logging into
the old web-page:

    https://trade.tastytrade.com/index.html#/transactionHistoryPage

This should allow you to download the old style history data and run my
script on the data. At least a temporary solution...

best regards,

Florian La Roche

**Comment by alneven** [comment]
After the 1st of February, this is no longer feasible.

the old platform was shut down

**Comment by Kotoriii** [comment]
I am afraid a lot of things have changed in the new transaction history. I will contact support and ask if there's a way they can provide me last year's history with the old template, but I wouldn't hold my breath

**Comment by Kotoriii** [comment]
> Thank you for your reply.  You can simply export the transaction history from the desktop platform, which did not ever change the format.  In any case, since we deprecated the old web browser platform, we do not have a way to export the old transactions filter.

Needless to say, the desktop platform's output is also different and doesn't work with the script. I wonder how I can file my 2023 taxes now :D

**Comment by sebastianhaberey** [comment]
Aww that sucks. I fully understand the work that is involved in maintaining an open source project, though.

**Comment by laroche** [comment]
The new format should be supported now. Please test and report back.
Closing this issue, please open a new one for updated/new requests.

Thanks a lot,

Florian La Roche

**Comment by sebastianhaberey** [comment]
Good news! 🎉
