### ISSUE TITLE
Net Liquidating Value is wrong

### ISSUE THREAD

**Issue by quantx-heiko** [laroche/tastyworks-pnl#43]
With the following attached dataset which is a Put Debit Spread, the summary shows a wrong Net Liquidating Value.` is displayed wrong.
[MES Put Debit Spread.csv](https://github.com/user-attachments/files/17129622/MES.Put.Debit.Spread.csv)

As all open trades are closed by the end of the year, the Net Liquidation Value is expected to be the same as the Cash Balance value.

`                                           2024`
`...`
`KAP+KAP-INV                              -38.16`
`KAP+KAP-INV KErSt+Soli                     0.00`
`KAP+KAP-INV Verlustvortrag               -10.06`
`Cash Balance USD                         958.58`
`Net Liquidating Value                    690.54`
`Net Liquidating Value EUR                618.43`
`Time Weighted Return USD                 -30.95`
`Time Weighted Return EUR                 -32.47`

I analyzed that issue. The root cause is the sorting of the transaction history in line 1162 (https://github.com/laroche/tastyworks-pnl/blob/a82be9e0d02150dc8207bab0c7fff0786f413d02/tw-pnl.py#L1162). After sorting the last record of the year no longer hold necessarily the last transaction. So the last net total value is not always the correct one anymore.

This issue is solved in my opinion by removing the sorting in line 1162. But I don't know if there was any special reason why this sorting has been implemented. May be @laroche has an idea.

**Comment by laroche** [comment]
Nice report, thanks for finding this.

The sort gives nicer output (sorted for Stock,Dividends,Options,Interest).

I've committed a rough hack to fix the statistics, hope the report is now ok.

Closing this issue, please reopen if it doesn't work or you find new items that are not correct.

best regards,
Thanks a lot,

Florian La Roche

**Comment by quantx-heiko** [comment]
Hi Florian,
thank you for your quick fix. Its working for me.
