### ISSUE TITLE
Problem with bmf_force = True

### ISSUE THREAD

**Issue by flanello** [laroche/tastyworks-pnl#7]
With the following data, a runtime error is generated when `bmf_force = True` is set (it works with `bmf_force = False`)

```
Date/Time,Transaction Code,Transaction Subcode,Symbol,Buy/Sell,Open/Close,Quantity,Expiration Date,Strike,Call/Put,Price,Fees,Amount,Description,Account Reference
09/23/2020 9:38 PM,Trade,Buy to Close,RUT,Buy,Close,8,10/30/2020,1530,P,98.19,2.53,-78552,Bought 8 RUT 10/30/20 Put 1530.00 @ 98.19,Individual...00
09/23/2020 9:30 PM,Trade,Buy to Close,RUT,Buy,Close,1,10/30/2020,1530,P,97.69,0.32,-9769,Bought 1 RUT 10/30/20 Put 1530.00 @ 97.69,Individual...00
08/24/2020 9:37 PM,Trade,Sell to Open,RUT,Sell,Open,1,10/30/2020,1530,P,60.96,1.322,6096,Sold 1 RUT 10/30/20 Put 1530.00 @ 60.96,Individual...00
08/24/2020 9:35 PM,Trade,Sell to Open,RUT,Sell,Open,6,10/30/2020,1530,P,61.16,7.902,36696,Sold 6 RUT 10/30/20 Put 1530.00 @ 61.16,Individual...00
08/24/2020 9:34 PM,Trade,Sell to Open,RUT,Sell,Open,2,10/30/2020,1530,P,60.97,2.634,12194,Sold 2 RUT 10/30/20 Put 1530.00 @ 60.97,Individual...00
```

**Comment by laroche** [comment]
I've fixed this bug in the newest commit.

Please note that you should NOT be using this option for tax statements. This option will add losses from selling
options where you only need to sum up losses from bought options for the tax statement.

best regards and thanks for the test case,
closing this report,

Florian La Roche

**Comment by flanello** [comment]
Thanks for fixing it. And thanks for the clarification.

My idea is to use this option to sum up all loses from selling and buying options. Could be useful for line 22 of KAP2020:
"In den Zeilen 18 und 19 enthaltene Verluste ohne Verluste aus der Veräußerung von Aktien"

**Comment by laroche** [comment]
Ok, that should work ok.

Maybe I can add counters for stock and non-stock losses in the future to support this more officially.

best regards,

Florian La Roche
